on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      # Need to checkout to read the markdown file
      - uses: actions/checkout@v2
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repos-file: 'repos.md'
